let x = 10;    // Basic assignment
x += 5; 
console.log(x); // x = x + 5 → 15
x -= 3;
console.log(x);        // x = x - 3 → 12
x *= 2;
console.log(x);        // x = x * 2 → 24
x /= 4; 
console.log(x);       // x = x / 4 → 6
x %= 4; 
console.log(x);       // x = x % 4 → 2